[window]
title          = "Fly-In"
min_width      = 600
bg_color       = 0x282828ff


[hub]
show_name      = false
text_color     = 0xffffffff


[connection]
show_capacity  = true
text_color     = 0xC0C0C0ff


[sizing]
space          = 54
padding_x      = 64
padding_y      = 120
